apiVersion: apps/v1
kind: Deployment
metadata:
  name: utility-payment
  namespace: banking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: utility-payment
  template:
    metadata:
      labels:
        app: utility-payment
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 3; done']
        - name: wait-for-eureka
          image: busybox
          command: ['sh', '-c', 'until nc -z service-registry 8081; do echo waiting for eureka; sleep 3; done']
      containers:
        - name: utility-payment
          image: sudhakar20000/ib-utility-payment:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/banking_core?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root1234"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://service-registry:8081/eureka/"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_ZIPKIN_BASE_URL
              value: "http://zipkin:9411"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: utility-payment
  namespace: banking
spec:
  selector:
    app: utility-payment
  ports:
    - port: 8085
      targetPort: 8085
